services:

  jupyter:
    build: notebooks
    ports:
      - '8888:8888'
    volumes: 
      - .:/home/jovyan/

  ops:
    build: src
    volumes: 
      - ./src:/home/app/src
      - ./data:/home/app/data
      - ./notebooks:/home/app/notebooks
      - ./models:/home/app/models
      - ./scripts:/home/app/scripts
      - ./config:/home/app/config
      - ./tests:/home/app/tests

    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t