services:

  jupyter:
    build: notebooks
    ports:
      - '8888:8888'
    volumes: 
      - .:/home/jovyan/

  devops-test:
    build: src
    volumes: 
      - ./src:/home/app/
      - ./data:/home/app/
      - ./notebooks:/home/app/

    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t